[[section-building-block-view]]


== Building Block View

=== Whitebox Overall System

[plantuml]
----
@startuml
actor User

package Program {
component Langfuck

note right of Langfuck
Transpiles / lexes the file.
end note

component Parser

note right of Parser
Parses the file.
end note

component Interpreter
note right of Interpreter
Interprets the file.
Outputs to stdout
end note

Langfuck --> Parser : Parses the lexed tokens
Parser --> Interpreter : Provides the parsed tokens


}


User --> Langfuck : Inputs source code and language file


@enduml
----



_**The user only uses one program, but in the program there are three key components: Langfuck itself, the Parser and then the Interpreter.**_

Contained Building Blocks::

* Langfuck
* Parser
* Interpreter

[options = "header", cols="1,2e"]
|===
|Name|Description
|Langfuck|Reads source code and transpiles it into brainfuck code
|Parser|Does Syntax analysis
|Interpreter|Runs the brainfuck code
|===



==== Langfuck
Langfuck reads the source code and maps it to the language file input by the user. Langfuck then takes this input and transpiles it into brainfuck code.



==== Parser

_The parser does syntax analysis (i.E is the loop closed, is there any loop ending that doesn't belong here).  It also transforms it into Parsertokens_

==== Interpreter

_Takes the token from the Parser and executes the code_