[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexer = {path = "../lexer"}
peekmore = {version = "1.0.0", features = ["smallvec"]}

[lib]
name = "parser"
path = "src/lib.rs"
