[package]
name = "benchmarks"
version = "0.2.0"
edition = "2021"


[dependencies]
interpreter = {path = "../interpreter"}
parser = {path = "../parser"}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "interpreter_benchmark"
harness = false