name: CI

on:
  push:
    branches: [ main ]
    paths:
      - benchmarks/*
      - interpreter/*
      - lexer/*
      - parser/*
      - Cargo.toml
  pull_request:
    branches: [ main ]
    paths:
      - benchmarks/*
      - interpreter/*
      - lexer/*
      - parser/*
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo c --verbose
    - name: Run tests
      run: cargo test --verbose
