name: CI

on:
  push:
    branches: [ main ]
    paths:
      - !.github/*
      - !brainfuck-example/*
  pull_request:
    branches: [ main ]
    paths:
      - !.github/*
      - !brainfuck-example/*
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: rustfmt --check
